# Generated by Django 4.1 on 2022-09-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('muscles', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Microcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('length', models.IntegerField()),
                ('daysOn', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutplan.microcycle')),
            ],
        ),
    ]
